# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetRestore@1

- task: Npm@1
- task: DotNetCoreCLI@2
  inputs:
   command: restore
   projects: 'WebApp/*.csproj'

- task: SonarCloudPrepare@1
  displayName: Prepare SonarCloud Analysis config
  inputs:
    SonarCloud: SonarCloud
    projectKey: MyAzureSubscription  
- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: 'WebApp/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'WebApp.UnitTest/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: SonarCloudAnalyze@1
  displayName: Run SonarCloud analysis

- task: SonarCloudPublish@1
  displayName: Publish SonarCloud QualityGate result  
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--no-build --configuration $(buildConfiguration)  --output $(Build.ArtifactStagingDirectory)'
    projects: 'WebApp/*.csproj'
    publishWebProjects: false
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  condition: succeeded()