# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: WebApp.Database/WebApp.Database.sqlproj
    msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Dacpac file
  inputs:
   ArtifactName: dacpac

- task: SqlAzureDacpacDeployment@1
  displayName: Azure SQL deployment 
  inputs:
    azureConnectionType: ConnectedServiceNameARM
    azureSubscription: 'Free Trial(4a80b6cd-158f-4bf0-bceb-0eb3fab4e5e6)'' 
    AuthenticationType: server
    DatabaseName: mytestdb 
    SqlUsername: dbadmin 
    SqlPassword: DBAdm1n01 
    deployType: DacpacTask
    DacpacFile: $(Build.ArtifactStagingDirectory)/dacpac
